apiVersion: apiextensions.k8s.io/v1
kind: CustomeResourceDefintion
metadata:
  name: flighttickets.flights.com
spec:
  scope: "Namespaced" # or you can set to clusted
  group: flights.com # used in the apiversion of the defintion
  names: 
    kind: FlightTicket
    singular: flightticket
    plural: flighttickets
    shortNames:
      - ft
  versions:
  - name: "v1"
    served: true
    storage: true

    schema:
      openAPIV3schema: 
        type: object
        properties:
          spec: 
            type: object
            properties:
              from: 
                type: string
              to:
                type: string
              number: 
                type: integer
                minimum: 1
                maximum: 10
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: internals.datasets.kodekloud.com
spec:
  group: datasets.kodekloud.com
  versions:
    - name: v1
      served: false
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                internalLoad:
                  type: string
                range:
                  type: integer
                percentage:
                  type: string
  scope: "Namespaced"
  names:
    plural: internals
    singular: internal
    kind: Internal
    shortNames:
    - int