apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding # kubectl get rolebindings or kubectl describe rolebinding <name>
metadata:
  name: cluster-admin-role-binding
subjects:
- kind: User
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-administrator
  apiGroup: rbac.authorization.k8s.io