apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # kubectl get roles or kubectl describe role developer
metadata:
  name: cluster-administrator
rules:
- apiGroups: [""]
  resources: ["nodes"] # cluster role can also be set to namespace scoped like pods
  verbs: ["list", "get", "create", "delete"]