apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod # kubectl get pods --selector app=App1 (e.g. kubectl get pods --selector bu=finance
                   # kubectl get pods --selector env=prod,bu=finance,tier=frontend
  annotations:
    buildversion: "1.34" # annotations are used for integration purpose
spec:
  containers:
    - name: nginx-container
      image: nginx
      args: ["10"] # not needed, you can add arg like this as needed (Entrypoint in )
      env:
        - name: APP_COLOR
          value: pink
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"