apiVersion: rbac.authorization.k8s.io/v1
kind: Role # kubectl get roles or kubectl describe role developer
metadata:
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["ConfigMap"]
  verbs: ["create"]