apiVersion: v1
kind: PersistentVolumeClaim # defined by user to claim based on capacity, access mode, volume mode, and storage class
metadata:
  name: mypvc
spec:
  selector:
    matchLabels:
      name: my-pv
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

