apiVersion: v1
kind: PersistentVolume # PeristentVolume is defined by admin
metadata:
  name: pv-vol1
  labels:
    name: my-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Recycle or delete
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs: # awsElasticBlockStore:
    path: /tmp
    server: 172.17.0.2
  
