apiVersion: v1
kind: PersistentVolumeClaim # defined by user to claim based on capacity, access mode, volume mode, and storage class
metadata:
  name: mypvc
spec:
  storageClassName: google-storage
  resources:
    requests:
      storage: <Size>
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

