apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
  labels:
    name: random-number-generator
spec:
  volumes: # all details go into the pod, which is a drawback
  - name: data-volume
    hostPath: # awsElasticBlockStore:
      path: /data # volumeID: <volume-id> , this must have provisioned before
      type: Directory # fsType: ext4
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["shuf -i o-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
