apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mysql-h
  replicas: 3 # each pod gets a dns record
  # podManagementPolicy: Parallel (if you don't want it to be ordered)
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers: 
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      # only required only for deployment if you want to subdomain: mysql-h  it uses this subdomain
      # hostname: mysql-pod # it uses this subdomain
  volumeClaimTemplates: # when you want to have different volume for each pod
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
