apiVersion: v1
kind: Pod
metadata:
  name: sample-webapp-color
  labels:
    name: sample-webapp-color
spec:
  containers:
  - name: sample-webapp-color
    image: sample-webapp-color
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    envFrom:
      - configMapRef:
          name: app-config
