# imperative and it is encoded (not encrypted) in the server
# Helm secrets and Helm valut is better way to use secrets
# kubectl create secret \
#               app-config --from-literal=APP_COLOR=red or from file
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_HOST: adssda== # encoded --> `echo n 'mysql' |base64` 

# to decode --> `echo 'mysql' |base64 --decode` 